ARG VERSION=v3.2.1
FROM alpine:3.21 AS builder
# Install gettext to get envsubst
RUN apk add --no-cache gettext

FROM prom/prometheus:${VERSION}
USER root

# We copy the binary, but we also have to hope the Busybox environment 
# has the required C libraries. If this still fails, Option 1 is your best bet.
COPY --from=builder /usr/bin/envsubst /usr/local/bin/envsubst

COPY prom.yml /etc/prometheus/prom.yml.template
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
CMD ["--config.file=/etc/prometheus/prom.yml", "--storage.tsdb.path=/prometheus"]