FROM alpine:3.21 AS builder
RUN apk add --no-cache gettext

FROM prom/prometheus:v3.10.0
USER root

# Copy envsubst AND the required libraries
COPY --from=builder /usr/bin/envsubst /usr/local/bin/envsubst
COPY --from=builder /usr/lib/libintl.so* /usr/lib/
COPY --from=builder /usr/lib/libunistring.so* /usr/lib/

COPY prom.yml /etc/prometheus/prom.yml.template
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
CMD ["--config.file=/etc/prometheus/prom.yml", "--storage.tsdb.path=/prometheus"]