global:
  scrape_interval: 15s # Default scrape interval

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'voima-api'
    scheme: http
    static_configs:
      - targets: ['voima-api.railway.internal:4000']
    metrics_path: '/metrics'
    basic_auth:
      username: ${VOIMA_METRICS_USER}
      password: ${VOIMA_METRICS_PASSWORD}

  # ? TODO: add more services here
  # - job_name: 'your-job-name'
  #   scheme: https
  #   static_configs:
  #     - targets: ['URL_GOES_HERE']
  #   basic_auth:
  #     username: HTTP_AUTH_USERNAME_GOES_HERE
  #     password: HTTP_AUTH_PASSWORD_GOES_HERE